package com.cwsn.mobileapp.model.profile

data class User(
    val aadhaar_number: String,
    val active_status: Int,
    val app_login: Int,
    val avatar: String,
    val created_at: String,
    val created_by: Any,
    val created_ip: Any,
    val current_team_id: Any,
    val dark_mode: Int,
    val date_of_birth: Any,
    val date_of_joning: String,
    val email: String,
    val email_verified_at: Any,
    val f_husband_name: String,
    val gender: String,
    val id: Int,
    val messenger_color: String,
    val name: String,
    val nature_appointment: String,
    val profile_photo_path: String,
    val profile_photo_url: String,
    val school_id: String,
    val status: String,
    val updated_at: String,
    val updated_by: Any,
    val updated_ip: Any,
    val user_role: String,
    val user_role_type: String,
    val username: String,
    val whatsapp_number: String
)